---
title: "STATS 810 Fall 2022, Homework 9. <br>Internet repositories for collaboration and open-source research: git and GitHub"
output:
  html_document:
    toc: no

---
## Objectives

* Git has become central to collaborative computing, sharing of data and code, and open source software. A professional statistician should have at least a working knowledge of git. Git is slowly becoming incorporated into more undergraduate and graduate courses, but likely this class spans a wide range from git novices to experts. If this assignment is trivial for you, consider helping others who are new to git.

* GitHub is the largest git-based internet repository, but others (such as Bitbucket) also use git. You can use git to build a local repository on your own computer, though in practice it is usually convenient to have the repository linked to an internet site.

* Our tasks are 

    i.  Learn some ways to think about what a git repository is and how it works.

    ii. Follow the instructions below to practice going through the process of editing a GitHub repository, making a fork, and submitting a pull request.

    iii.  Use the self-teaching materials at [GitHub Learning Lab](https://lab.github.com/) or [Atlassian](https://www.atlassian.com/git/tutorials) to spend an hour or so advancing your knowledge of git. The Atlassian tutorials are better for learning command-line git, but they teach in the context of Bitbucket which is currently less popular than GitHub although both are based around the same git program. The [Introduction to GitHub module](https://lab.github.com/githubtraining/introduction-to-github) may be a good starting point for beginners. Alternatively, browse Karl Broman's practical and minimal [git/github tutorial](http://kbroman.org/github_tutorial/) which this assignment draws on.

    iv. Report briefly on your past experience with git, and what you learned while studying for this homework. Edit the `hw09.Rmd` file in the `810f22` git repository, compile this to html (for example, using Rstudio) and submit your report via Canvas as an html file.
    
  

# My response:
After finishing my undergraduate degree I worked for a few years in data science 
roles. I many of these roles I collaborated on projects through the use of git 
and github. Before starting the PhD I completed a masters degree and used git / Github
in many courses. I mostly work with git using its command line api. Despite 
years of using git I would say my knowledge is still fairly superficial and don't 
know much beyond creating my own branch, pushing changes, pulling changes, and 
making pull requests. Occasionally if I need to retract changes I have committed 
I will use `git reset`. 

Through reading the tutorials on Atlassian, I learned about git subtree. I had 
always imagined that it would be a bad idea to clone one repository within another
but now after reading this it makes a lot more sense, in particular if you are 
building software that has dependencies which are likely continually updating. 
I also spent some time reading in depth about `git reset`, `git checkout`, and `git revert`.
As I had mentioned before, I have often used `git reset`, but this has almost 
exclusively been to remove a file from the staging area if I decided not to commit 
changes for that particular file. Through reading, I learned about how the different 
commands and different arguments correspond to changes the current working
directory, staging area, and commit history. Before I had avoided making grave
errors while using `git reset` by simply using it for specific files, but know that 
I know about the `--mixed`, `--soft`, and `--hard` arguments I will be less likely to 
make catastrophic errors when using `git reset` with a broader scope.
